version: "3.8"

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: ads-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 03XH*jfN8y'HcX+~
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/initdb/init.sql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  backend:
    build: ./server
    restart: always
    environment:
      DB_USER: postgres
      DB_PASSWORD: 03XH*jfN8y'HcX+~
      DB_HOST: db       # hostname of postgres container
      DB_NAME: ads-db
      DB_PORT: 5432
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build: ./client
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata: